---
name: 'publish-preview'

on:  # yamllint disable-line rule:truthy
    pull_request:
        types: ['edited', 'opened', 'reopened', 'synchronize']

jobs:
    publish-preview:
        uses: 'Nostra-Inc/iac-workflow/.github/workflows/publish-preview-reusable.yaml@NOSTRAPROJ-145'
        secrets:
            token: '${{ secrets.GITHUB_TOKEN }}'
