---
name: 'publish-reusable'

on:  # yamllint disable-line rule:truthy
    workflow_call:
        secrets:
            token:
                required: true

jobs:
    publish:
        runs-on: 'ubuntu-20.04'
        steps:
            # https://github.com/actions/checkout
            - name: 'checkout'
              uses: 'actions/checkout@v3'
              with:
                  fetch-depth: 0

            # https://github.com/WyriHaximus/github-action-get-previous-tag
            - name: 'get-previous-tag'
              id: 'latest-tag'
              uses: 'WyriHaximus/github-action-get-previous-tag@v1.2.2'
              with:
                  fallback: 'fallback-token'

            # Enforce start at v1.0.0
            # https://github.com/mathieudutour/github-tag-action
            - name: 'first-tag'
              id: 'first-tag-version'
              uses: 'mathieudutour/github-tag-action@v6.1'
              if: "${{ steps.latest-tag.outputs.tag == 'fallback-token' }}"
              with:
                  github_token: '${{ secrets.token }}'
                  custom_tag: '1.0.0'
                  dry_run: false

            # Calculate the next SemVer
            # https://github.com/mathieudutour/github-tag-action
            - name: 'semver-tag'
              id: 'calculate-tag-version'
              uses: 'mathieudutour/github-tag-action@v6.1'
              if: "${{ steps.latest-tag.outputs.tag != 'fallback-token' }}"
              with:
                  github_token: '${{ secrets.token }}'
                  custom_release_rules: 'MAJOR:major,MINOR:minor,PATCH:patch'
                  dry_run: false
